### ISSUE TITLE
Интеграция с Trello для маразматикоч

### ISSUE THREAD

**Issue by ukudulukah** [alordash/BotSmartScheduler#104]
Привет! Почему-то не постигаю как поженить бота с Trello. Можно более подробно последовательность шагов для альтернативно-одаренных пользователей вроде меня? По /trello только получаю сообщение о том, что к чату не прикреплена ни одна доска.

**Comment by alordash** [comment]
Здравствуйте, привязка к трелло производится исключительно в ЛС бота. В чате по команде /trello бот будет показывать только привязанную доску. Сделано это для безопасности, чтобы другие пользователи чата не смогли воспользоваться вашим trello-api ключем.

**Comment by ukudulukah** [comment]
Спасибо! Всё получилось, просто затупил немношк.
