### ISSUE TITLE
Incorrect processing of "через полчаса" ("in half an hour", rus) / Некорректно обрабатывается "через полчаса"

### ISSUE THREAD

**Issue by blackleadsu** [alordash/BotSmartScheduler#2]
If you type "Оповестить о чем-либо через полчаса" bot does not recognize "через полчаса"  ("in half an hour", rus) as indication of time and assigns the reminder for 19 hours from the current time with the text "Оповестить о чем-либо через полчаса" (as is).

Если напечатать  "Оповестить о чем-либо через полчаса" бот не распознает "через полчаса" как указание времени, и назначит напоминалку на момент через 19 часов от текущего времени с текстом "Оповестить о чем-либо через полчаса".

P.s.
Timezone: GMT +05:00;
Screenshot: https://yadi.sk/i/CpZaeBwATOvhZA

**Comment by alordash** [comment]
Thank you for report.
Fixed in [this commit](https://github.com/alordash/BotSmartScheduler/commit/2f7e258cb856f966eba1de3160b2ba78a5da4c52).
