### ISSUE TITLE
Добавить лицензию

### ISSUE THREAD

**Issue by NChechulin** [alordash/BotSmartScheduler#3]
Каждому проекту рекомендуется иметь лицензию, чтобы люди знали, можно ли копировать и распространять код. Я советую воспользоваться [choosealicense](https://choosealicense.com/) при выборе лицензии.

**Comment by alordash** [comment]
Благодарю за помощь.
[Лицензия добавлена](https://github.com/alordash/BotSmartScheduler/commit/c996b2a585c5b9aeb925e493c96af150bce33ad0).
