### ISSUE TITLE
Инструкция по запуску

### ISSUE THREAD

**Issue by mcravtov** [alordash/BotSmartScheduler#4]
Было бы не плохо получить FAQ по запуску, интуитивно из кода понятно, но если хочется все на своем сервере запустить?

**Comment by alordash** [comment]
Спасибо за обращение, FAQ будет написан после добавления поддержки голосовых сообщений, так как для их распознавания нужен отдельный токен API.

**Comment by alordash** [comment]
Добавлены инструкции по установке в #14 .
